-- Tabela de Categorias (BIGINT no lugar de SERIAL)
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Modificado
    name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Despesas (BIGINT no lugar de SERIAL)
CREATE TABLE expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Modificado
    description VARCHAR(255) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    expense_date DATE NOT NULL,
    category_id BIGINT REFERENCES categories(id),  -- Modificado
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);